alias cp="rsync -ah --progress"
alias mv="rsync -ah --progress --remove-source-files $1 $2 && find $1 -type d -empty -delete"
alias rm="rm -iv"
alias mkdir="mkdir -p"
alias apt-get="sudo apt-get"
alias vim="nvim"
alias ..="cd .."
alias ....="cd ...."
alias rmd="rm -rf"
alias ls="ls -aFh --color=always"
alias mktar="tar -cvf"
alias mkzip="zip -rv"
alias cat="bat"
alias pip-install="pip3 install --user"
alias send="wormhole send"
alias receive="wormhole receive"
alias mkcd="_(){ mkdir -p $1; cd $1; }; _"
alias find="find . -name $1"
alias gstatus="git status -sb"
alias gadd="git add"
alias gcommit="git commit -m"
alias gfetch="git fetch"
alias gmerge="git merge"
alias gpush="git push"
alias gdiff="git diff --color-words"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
